# Generated by Django 2.2.2 on 2021-01-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('no', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('sal', models.IntegerField()),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
    ]
